name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
# client checks
  client-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          #cache: 'npm'
          #cache-dependency-path: ./client/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      
# server checks
  server-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          #cache: 'npm'
          #cache-dependency-path: ./server/package-lock.json

      - name: Install Dependencies
        run: npm ci

      # verify docker build works
      - name: Check Docker Build
        run: docker build . --file Dockerfile

# deployment (only runs if the client and server checks pass)
  deploy:
    needs: [client-checks, server-checks] # wait till client and server checks pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only run on main branch
    
    steps:
      - name: Deploy to Render
        # set render deploy hook in github repo settings -> secrets
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        
     
